using System;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;

namespace AI_Interface.Services;

/// <summary>
/// Runs a local <b>SearXNG</b> instance in Docker. Install pulls <c>searxng/searxng</c>, writes a minimal
/// <c>settings.yml</c> that turns on the JSON output format + disables the rate limiter (both required for
/// the app's <c>?format=json</c> API calls), and starts a container mapping host port 8888 → 8080. Remove
/// stops/deletes the container, drops the image, and deletes the generated config. Docker is required;
/// when it's absent the methods throw a clear <see cref="InvalidOperationException"/>.
/// </summary>
public sealed class SearxngInstaller : ISearxngInstaller
{
    internal const string ContainerName = "searxng-carnelian";
    internal const string Image = "searxng/searxng";
    internal const int HostPort = 8888;

    public string LocalUrl => $"http://localhost:{HostPort}";

    private static string ConfigDir =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "AI_Interface", "searxng");

    public async Task<bool> IsRunningAsync(CancellationToken ct = default)
    {
        var (code, output) = await RunDockerAsync(ct, ignoreErrors: true,
            "ps", "--filter", $"name={ContainerName}", "--filter", "status=running", "--format", "{{.Names}}");
        return code == 0 && output.Contains(ContainerName, StringComparison.Ordinal);
    }

    public async Task InstallAsync(IProgress<string>? progress, CancellationToken ct)
    {
        if (!await DockerAvailableAsync(ct).ConfigureAwait(false))
            throw new InvalidOperationException(
                "Docker is required to run SearXNG locally. Install Docker (https://docs.docker.com/get-docker/), " +
                "make sure it's running, and try again.");

        progress?.Report("Preparing SearXNG configuration…");
        Directory.CreateDirectory(ConfigDir);
        var settingsPath = Path.Combine(ConfigDir, "settings.yml");
        if (!File.Exists(settingsPath))
            await File.WriteAllTextAsync(settingsPath, BuildSettingsYaml(GenerateSecretKey()), ct).ConfigureAwait(false);

        // Recreate cleanly so a re-install always picks up the latest config / a fixed port.
        progress?.Report("Removing any previous SearXNG container…");
        await RunDockerAsync(ct, ignoreErrors: true, "rm", "-f", ContainerName).ConfigureAwait(false);

        progress?.Report("Pulling & starting SearXNG (the first run downloads the image — this can take a minute)…");
        var (code, output) = await RunDockerAsync(ct, ignoreErrors: true, RunArgs(HostPort, ConfigDir)).ConfigureAwait(false);
        if (code != 0)
            throw new InvalidOperationException($"Failed to start SearXNG: {Tidy(output)}");

        progress?.Report($"SearXNG is running at {LocalUrl}.");
    }

    public async Task RemoveAsync(IProgress<string>? progress, CancellationToken ct)
    {
        if (!await DockerAvailableAsync(ct).ConfigureAwait(false))
            throw new InvalidOperationException("Docker isn't available, so there's nothing to remove.");

        progress?.Report("Stopping & removing the SearXNG container…");
        await RunDockerAsync(ct, ignoreErrors: true, "rm", "-f", ContainerName).ConfigureAwait(false);

        progress?.Report("Removing the SearXNG image…");
        await RunDockerAsync(ct, ignoreErrors: true, "rmi", Image).ConfigureAwait(false);

        try
        {
            if (Directory.Exists(ConfigDir))
                Directory.Delete(ConfigDir, recursive: true);
        }
        catch { /* best-effort config cleanup */ }

        progress?.Report("SearXNG removed.");
    }

    // --- pure, testable helpers ----------------------------------------------------------------

    /// <summary>The <c>docker run</c> argument vector that starts the container.</summary>
    internal static string[] RunArgs(int port, string configDir) => new[]
    {
        "run", "-d",
        "--name", ContainerName,
        "--restart", "unless-stopped",
        "-p", $"{port}:8080",
        "-v", $"{configDir}:/etc/searxng",
        Image
    };

    /// <summary>A minimal SearXNG config that turns on the JSON API + disables the limiter (both needed for
    /// programmatic <c>?format=json</c> access) on top of the image defaults.</summary>
    internal static string BuildSettingsYaml(string secretKey) =>
        "# Generated by Carnelian — enables the JSON API the app needs.\n" +
        "use_default_settings: true\n" +
        "server:\n" +
        $"  secret_key: \"{secretKey}\"\n" +
        "  limiter: false\n" +
        "  image_proxy: false\n" +
        "search:\n" +
        "  formats:\n" +
        "    - html\n" +
        "    - json\n";

    private static string GenerateSecretKey() =>
        Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();

    // --- Docker process plumbing ---------------------------------------------------------------

    private async Task<bool> DockerAvailableAsync(CancellationToken ct)
    {
        var (code, _) = await RunDockerAsync(ct, ignoreErrors: true, "--version").ConfigureAwait(false);
        return code == 0;
    }

    /// <summary>
    /// Runs <c>docker</c> with the given argument vector (no shell, so paths with spaces are safe), captures
    /// stdout+stderr, and returns (exit code, combined output). A missing <c>docker</c> binary yields
    /// (-1, "docker not found") when <paramref name="ignoreErrors"/>, else throws.
    /// </summary>
    private static async Task<(int Code, string Output)> RunDockerAsync(
        CancellationToken ct, bool ignoreErrors, params string[] args)
    {
        using var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "docker",
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                CreateNoWindow = true
            }
        };
        foreach (var a in args)
            process.StartInfo.ArgumentList.Add(a);

        try
        {
            if (!process.Start())
                throw new InvalidOperationException("Could not start the docker process.");
        }
        catch (Win32Exception)
        {
            if (ignoreErrors)
                return (-1, "docker not found");
            throw new InvalidOperationException("Docker is not installed or not on PATH.");
        }

        var stdout = await process.StandardOutput.ReadToEndAsync(ct).ConfigureAwait(false);
        var stderr = await process.StandardError.ReadToEndAsync(ct).ConfigureAwait(false);
        await process.WaitForExitAsync(ct).ConfigureAwait(false);

        return (process.ExitCode, (stdout + stderr).Trim());
    }

    private static string Tidy(string output)
    {
        var trimmed = output.Trim();
        return trimmed.Length <= 300 ? trimmed : trimmed[..300] + "…";
    }
}
